// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for this app. Only Android and web are configured.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS has not been configured for this Firebase project.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS has not been configured for this Firebase project.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows has not been configured for this Firebase project.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux has not been configured for this Firebase project.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyUkPBltYk0tGg8X62bCCOCvuCTnjRVGg',
    appId: '1:914607382752:android:348626b1b382c542fbf085',
    messagingSenderId: '914607382752',
    projectId: 'saas-management-du664',
    storageBucket: 'saas-management-du664.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6JEyfEnyjXeJetEBDj5mkA9N3-LBeJg',
    appId: '1:914607382752:web:d9fcbf0c700f822cfbf085',
    messagingSenderId: '914607382752',
    projectId: 'saas-management-du664',
    authDomain: 'saas-management-du664.firebaseapp.com',
    storageBucket: 'saas-management-du664.firebasestorage.app',
    measurementId: 'G-R0JRPPSH84',
  );
}